const api = typeof window !== 'undefined' && window.downTube ? window.downTube : null;

export const downTube = {
  getSettings: () => api?.getSettings?.(),
  saveSettings: (s) => api?.saveSettings?.(s),
  getDefaultOutputDir: () => api?.getDefaultOutputDir?.(),
  chooseOutputDir: () => api?.chooseOutputDir?.(),
  chooseCookiesFile: () => api?.chooseCookiesFile?.(),
  startDownload: (args) => api?.startDownload?.(args),
  startConversion: (args) => api?.startConversion?.(args),
  probeFormats: (url) => api?.probeFormats?.(url),
  fetchInfo: (url) => api?.fetchInfo?.(url),
  cancel: (id) => api?.cancel?.(id),
  getActiveDownloads: () => api?.getActiveDownloads?.(),
  getActiveConversions: () => api?.getActiveConversions?.(),
  getHistory: () => api?.getHistory?.(),
  getAppMode: () => api?.getAppMode?.(),
  clearHistory: () => api?.clearHistory?.(),
  showItemInFolder: (path) => api?.showItemInFolder?.(path),
  openPath: (path) => api?.openPath?.(path),
  getAppInfo: () => api?.getAppInfo?.(),
  chooseVideoFiles: () => api?.chooseVideoFiles?.(),
  checkForUpdates: () => api?.checkForUpdates?.(),
  showUpdateDialog: (info) => api?.showUpdateDialog?.(info),
  getUpdatePreferences: () => api?.getUpdatePreferences?.(),
  onProgress: (cb) => api?.onProgress?.(cb),
  onItemComplete: (cb) => api?.onItemComplete?.(cb),
  onDone: (cb) => api?.onDone?.(cb),
  onError: (cb) => api?.onError?.(cb),
  onConvertProgress: (cb) => api?.onConvertProgress?.(cb),
  onConvertComplete: (cb) => api?.onConvertComplete?.(cb),
  onConvertError: (cb) => api?.onConvertError?.(cb),
  onAppMode: (cb) => api?.onAppMode?.(cb),
  windowClose: () => api?.windowClose?.(),
  windowMinimize: () => api?.windowMinimize?.(),
  windowMaximizeToggle: () => api?.windowMaximizeToggle?.()
};
